### ISSUE TITLE
Pagination breaks link to content component

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#569]
Example in UX:
  select Tasks --> Stage Chooser
  click on barbell (or whatever it is) for stage-chooser.sh.tmpl 

This takes you to the Templates page, with a list of the templates.  Since the specific template "stage-chooser.sh.tmpl" is on "Page 2", it doesn't pop-out the right panel to display it. 

However, if you click on "All", or "Next Page", or "50" per page - it'll expand the right panel to show the template. 

Expected Behavior:
Should take me to Templates and pop-out the panel w/ the "stage-chooser.sh.tmpl" template, regardless of the items per page setting.

**Comment by Meshiest** [comment]
This issue occurs when the limited number of items in pagination is causing the stage-chooser template (determined by the route `/templates/stage-chooser.sh.tmpl`), which appears later than the first 20 items in the query, to not appear in the UX's data. When 50-All is selected, the UX gets the rest of the templates including stage-chooser and then can display the appropriate item from the given url route.

I will be working on a solution involving fetching the item from the API instead of waiting for the pagination to reach it should the item not be found in the first 20.

@galthaus
