### ISSUE TITLE
GUI: change state and bootenv of individual machines

### ISSUE THREAD

**Issue by mash-graz** [digitalrebar/provision#820]
could you please add the possibility of changing the state and bootenv of actual machines in the free version of the GUI resp. without the requirement of being   logged in at RackN? 

this is a real show stopper, if you want to utilize a least the most elementary operations of DRP via the GUI of the free version.

in general i don't like this particular form of open core marketing strategy and remote access to the GUI not very much. i definitely would prefer a local hosted GUI and downloadable/purchasable add-ons much more (e.g. for security reasons...). but that's a point, where we simply have to accept your decisions. i just want to express my personal opinion about it. nevertheless i think, that even in this kind of open core products, at least the most elementary operations should be always available...

**Comment by sygibson** [comment]
@mash-graz thank you for taking the time to provide feedback tot he team.

You can change the **_bootenv_**, **_stage_**, and **_workflow_** in the UI without a RackN login.  Go to the machines list, select the machine, then edit.  In the Edit panel you may change these options.  The current `Stable` portal (`portal.rackn.io`) does not support changing BootEnv; the 'Tip' portal (`tip.rackn.io`) does (due to community feedback).  In general; you should not change BootEnvs if you are using the Stage system.  Stages request the appropriate BootEnv for the stage and given workflow.

This has been validated this with the 'Tip' (`tip.rackn.io`) version of the UX on a tip DRP.   If this doesn't work with the latest tip pieces of the system  (there were some issues for a while), please re-open the issue.

Additionally, you can make all of these changes via the CLI (drpcli) via the appropriate top-level command (eg '**_stages_**, '**_bootenvs_**', '**_workflows_**' (for `tip` versions).  The CLI can be used in typical shell looping constructs to approximate "bulk" edit changes.  Of course, just about anything is possible via use of the API.

Please note that the Open Source components are 100% functional and capable, and many of the features and capabilities have been shaped based on community feedback.  As the sponsoring company for Digital Rebar Provision, RackN has contributed at no cost to the community; well over 10,000 hours of engineering work and resources to the overall product.

You may wish to review the license around the UX to understand that the intent of "free use" is CLI-only.  The Terms of Use are accessible via a few places in the UX, and you can find the links to them here for reference, as well:

  community use terms:  https://portal.rackn.io/eula/community.md
  rackn use terms:  https://portal.rackn.io/eula/rackn.md

We do value feedback from the community, and the rest of your commentary has been duly noted.  If you wish to discuss a commercial relationship, all your requests are available and can be addressed.

We are marking this Issue as closed, however, if you have further input or comments, please feel free to Comment on them on this issue.  Thank you.

**Comment by mash-graz** [comment]
@sygibson thanks for this very helpful advice!

> You can change the bootenv, stage, and workflow in the UI without a RackN login. Go to the machines list, select the machine, then edit. In the Edit panel you may change these options. The current Stable portal (portal.rackn.io) does not support changing BootEnv; the 'Tip' portal (tip.rackn.io) does...

i gave it a try and it works indeed as advised!
i couldn't notice any significant differences between tip and the stable portal, it just works the same in  both variants. it's only a little bit clumsy, because you have to clear the stage any time before you can set the bootenv, but the state is set again after saving the change. so it's a lot of useless clicking, but works in the end!

> Additionally, you can make all of these changes via the CLI (drpcli) via the appropriate top-level command (eg 'stages, 'bootenvs', 'workflows' (for tip versions). The CLI can be used in typical shell looping constructs to approximate "bulk" edit changes. Of course, just about anything is possible via use of the API.

yes -- and that's exactly the reason, why i have chosen your tool and i really like it! 
but i always feel a little bit responsible for other coworks as well, which often do not appreciate all this power of cli tools and well designed APIs so much, but  rather prefer GUIs and clicking odysseys. i therefore just wanted to make sure, that simple changes of the boot configuration can indeed be handled in both ways.

> Please note that the Open Source components are 100% functional and capable, and many of the features and capabilities have been shaped based on community feedback. As the sponsoring company for Digital Rebar Provision, RackN has contributed at no cost to the community

please, don't take me wrong. i really didn't want to criticize this split between the free core parts and the commercial component in general. it's perfectly acceptable to me. i just personally prefer open solutions even in my professional work most of the time. it's quite often not only the economic benefit, but the freedom of customisability and the vivid exchange of their user communities, which i really esteem as invaluable. in fact, i'm usually just trying to choose the most adequate option, and that's quite often a free one, because of its intrinsic qualities. but i also see the pragmatic necessities of economic survival of its developers and manufacturies. i therefore really respect any attempt, to find useful and exemplary answers in this challenge as well. when i expressed my point of view about this matter, it was just a kind of minimal active user feedback, which i still see as the very least, what user should give in return for very well made free software.

thanks!
