### ISSUE TITLE
intstall/update BootEnvs by URL

### ISSUE THREAD

**Issue by mash-graz** [digitalrebar/provision#854]
the `drpcli bootenvs install` command, which also automatically downloads the need iso file, is a really comfortable feature, but there are two minor improvements, which i would like to see:

1. because i'm building the disk images and the corresponding BootEnv yaml file by help of GitLabs CI system, where they are finally accessible via GitLab pages web service, i would prefer to enter just the URL of the remote BootEnv yaml file on the command line, instead of manually downloading this file in advance.

2. while the automatic iso download works quite well for the first installation, this doesn't apply to any further update of the BootEnv. this kind operation is very annoying in the present implementation. you can't simply destroy the old BootEnv and install a new one, because it's usually in use by one of the machines, the update command will not download the iso image, and the old replaced iso image and its exploded directory are not removed by any of this variants...

i really think, this very common operation could be improved a little bit...

**Comment by galthaus** [comment]
For item #1, you can do: **drpcli bootenvs update <bootenv name> <URL of yaml>**

For item #2, you may want to look at the **uploadiso** CLI command does the same thing but reposts the iso. 

You should be using checksums in your bootenv for the iso.  Upon uploading an iso, the checksum is checked and the image will re-exploded if the checksum is different.  The BootEnv will also be marked invalid if the checksum is different to indicate a failure.

You may also wish to check into building a content bundle instead of doing update/create calls because it handles the version concepts better.  

leading to:
GitLabs jobs that does
  * build bootenv image
  * build checksum
  * build bootenv yaml
  * build content indicating version

Deployment is done by:
  * drpcli content update 
  * drpcli bootenvs uploadiso <fred>

Lots of options.  Need to think about actually changing these commands.

**Comment by mash-graz** [comment]
> You may also wish to check into building a content bundle instead of doing update/create calls because it handles the version concepts better.

thanks for this intersting hint!
it could be indeed a better solution. but the [documentation about this capabilites](http://provision.readthedocs.io/en/tip/doc/arch/design.html#content-package-management) looks very arcane. so i'm not sure if it would really solve my needs,

in fact i was more asking about simply using an URL pointing to an remote yaml file instead of  a local file path in pt. 1

**Comment by galthaus** [comment]
Yes, that is what I meant to say, but it appears truncated in the above.

the text processing ate it.  Here it is again:
drpcli bootenvs update Name URL

**Comment by mash-graz** [comment]
`drpcli bootenvs update Name URL`

yes, that's exactly what i was looking for! 
but can i use this command also, if the BootEnv doesn't already exist?

**Comment by zehicle** [comment]
This was added into the community bootenvs

**Comment by galthaus** [comment]
I think all of this has been implemented and updated.
