### ISSUE TITLE
UX: new machine object can't modify bootenv or stage

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#864]
Reported by community member @lae 

* create new machine object
* try to modify the Stage or BootEnv on the new object fails

You must:

* create machine object
* save machine object
* open newly created machine object
* select "edit"
* now you can modify the Stage and/or BootEnv
* save changes

Video demonstrating issue: https://up.lae.is/u/newmachine.mp4

**Comment by galthaus** [comment]
Okay - this works with a ux tweak on the machines page.

The issue could be made worse if you have a default workflow.  If the system has a default workflow, any machine created without a workflow will use that workflow and potentially overwrite the selected options.  For example, a default workflow of discover with sledgehammer bootenv and discover stage will overwrite the selected values in create.  This is by design to keep those in sync.  Setting the default workflow to unset will generate the correct results assuming that you follow the same Stage and BootEnv relationship.
